name: pgpx

on:
  workflow_dispatch:
  push:
    tags: [ "v[1234].[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for darwin/amd64 (mac intel)
      run: |
        GOOS=darwin GOARCH=amd64 go build -o pgpx-mac-intel pgpx.go

    - name: Build for darwin/arm64 (mac Mx)
      run: |
        GOOS=darwin GOARCH=arm64 go build -o pgpx-mac-m pgpx.go

    - name: Upload artifact (mac intel)
      uses: actions/upload-artifact@v3
      with:
        name: pgpx-mac-intel
        path: ./pgpx-mac-intel

    - name: Upload artifact (mac Mx)
      uses: actions/upload-artifact@v3
      with:
        name: pgpx-mac-m
        path: ./pgpx-mac-m
