name: pgpx

on:
  workflow_dispatch:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        os: [ darwin ]
        product: [ pgpx ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Standardize HEAD Reference
      id: head_ref
      run: |
        echo "REF=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build binary for ${{ matrix.arch }}
      run: |
        GOOS=darwin GOARCH=${{ matrix.arch }} go build -o ${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }} ${{ matrix.product }}.go
        sha256sum -b ${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }} | awk '{ print $1; }' > ${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }}.sha256

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ env.REF }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md

    - name: Upload ${{ matrix.arch }} artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }}
        asset_name: ${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }}
        asset_content_type: application/octet-stream

    - name: Upload ${{ matrix.arch }} artifact SHA256 hash
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }}.sha256
        asset_name: ${{ matrix.product }}-${{ matrix.os }}-${{ matrix.arch }}.sha256
        asset_content_type: text/plain
  