name: pgpx

on:
  workflow_dispatch:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Retrieve branch information
      id: branch_info
      run: |
        echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> GITHUB_OUTPUT
        echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> GITHUB_OUTPUT
        echo "SOURCE_TAG::${GITHUB_REF#refs/tags/}" >> GITHUB_OUTPUT

    - name: Build for darwin/amd64 (mac intel)
      run: |
        GOOS=darwin GOARCH=amd64 go build -o pgpx-mac-intel pgpx.go

    - name: Build for darwin/arm64 (mac Mx)
      run: |
        GOOS=darwin GOARCH=arm64 go build -o pgpx-mac-m pgpx.go

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ steps.branch_info.outputs.SOURCE_TAG }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md

    - name: Upload mac intel artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pgpx-mac-intel
        asset_name: pgpx-mac-intel-${{ steps.branch_info.outputs.SOURCE_TAG }}
        asset_content_type: application/octet-stream

    - name: Upload mac Mx (M1, M2) artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pgpx-mac-m
        asset_name: pgpx-mac-m-${{ steps.branch_info.outputs.SOURCE_TAG }}
        asset_content_type: application/octet-stream
